
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost/uatschema
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
